const homecooks = [
  {
    name: "Panchami Devi",
    imgURL: "https://drive.google.com/uc?id=1P1tK47JDYZbPnYRRGXj6HZlBBQ2LMJMa",
    foodType: "biryani, north indian",
    quote: "Authentic homemade flavors delivered with love",
    rating: "4.5",
    noOfOrders: "153",
    minPrice: "88",
    dateOfJoining: "2023-05-25",
    dishes: {riceDelights: [{name: "Vegetable Biryani",
                            desc: "Fragrant basmati rice cooked with an assortment of fresh vegetables, aromatic spices, and herbs. This flavorful and colorful dish is a perfect balance of textures and tastes, making it a favorite among vegetarians and rice lovers.",
                            price: "₹79",
                            imgURL: "https://holycowvegan.net/wp-content/uploads/2019/01/vegetable-biryani-recipe-500x500.jpg"},
                           {name: "Chicken Biryani",
                            desc: "Fragrant basmati rice cooked with tender chicken pieces, aromatic spices, and a blend of herbs. This classic Indian dish is layered with flavors and served with raita (yogurt sauce) for a satisfying and aromatic meal.",
                            price: "₹99",
                            imgURL: "https://www.licious.in/blog/wp-content/uploads/2020/12/Hyderabadi-chicken-Biryani.jpg"},
                           {name: "Vegetable Pulao",
                            desc: "A medley of basmati rice and mixed vegetables cooked together with aromatic spices, creating a flavorful and colorful rice dish. Each spoonful is a delightful combination of textures and tastes, perfect for a wholesome meal.",
                            price: "₹85",
                            imgURL: "https://www.funfoodfrolic.com/wp-content/uploads/2022/05/Veg-Pulao-Blog.jpg"},
                           {name: "Lemon Rice",
                            desc: "Tangy and zesty, lemon rice is made by tossing cooked rice with a tempering of mustard seeds, curry leaves, peanuts, and a generous squeeze of fresh lemon juice. It's a refreshing and light option, bursting with citrusy flavors.",
                            price: "₹59",
                            imgURL: "https://www.whiskaffair.com/wp-content/uploads/2019/03/Lemon-Rice-2-3.jpg"},
                           {name: "Mushroom Biryani",
                            desc: "A delectable combination of basmati rice, fragrant spices, and succulent mushrooms. This vegetarian biryani is a burst of earthy flavors and is sure to satisfy both mushroom lovers and rice enthusiasts.",
                            price: "₹89",
                            imgURL: "https://production-media.gousto.co.uk/cms/mood-image/1485---10-Min-Mushroom-Biryani-With-Cucumber-Raita.jpg"},
                           {name: "Mutton Biryani",
                            desc: "Succulent mutton pieces cooked with basmati rice, aromatic spices, and a blend of herbs. This rich and flavorful biryani is a celebration of tender meat and fragrant rice, creating a memorable dining experience.",
                            price: "₹119",
                            imgURL: "https://www.licious.in/blog/wp-content/uploads/2022/03/Licious-Holi-2022-009-1-min-1024x1024-1-600x600.jpg"}],
            curryMagic:  [{name: "Palak Paneer",
                            desc: "Soft cubes of paneer (Indian cottage cheese) simmered in a luscious spinach gravy with aromatic spices. This vegetarian delight is not only rich in flavor but also packed with the goodness of spinach, making it a favorite choice among Indian food lovers.",
                            price: "₹99",
                            imgURL: "https://images.unsplash.com/photo-1589647363585-f4a7d3877b10?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFsYWslMjBwYW5lZXJ8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60"},
                           {name: "Chana Masala",
                            desc: "A popular North Indian dish made with chickpeas simmered in a flavorful and tangy tomato-based gravy, infused with aromatic spices. This vegetarian curry is hearty, protein-packed, and pairs well with rice, naan, or roti.",
                            price: "₹59",
                            imgURL: "https://www.archanaskitchen.com/images/archanaskitchen/0-Archanas-Kitchen-Recipes/2020/Amritsari_Chole_Masala_Recipe_Punjabi_Chole_Masala_Chana_Masala_4.jpg"},
                           {name: "Malai Kofta",
                            desc: "Deep-fried paneer and vegetable dumplings served in a creamy and rich cashew-based gravy, flavored with aromatic spices. This indulgent vegetarian dish is a true delight, offering a perfect combination of textures and flavors.",
                            price: "₹79",
                            imgURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs_n8Vl3qICMThV3QirKW9szqe64VidCEY_A&usqp=CAU"},
                           {name: "Butter Chicken",
                            desc: "Tender chicken cooked in a creamy and flavorful tomato-based gravy, enriched with butter and aromatic spices. This iconic Indian dish is a harmonious blend of tangy and creamy flavors, perfect to be savored with naan or rice.",
                            price: "₹129",
                            imgURL: "https://img.freepik.com/free-photo/curry-with-chicken-onions-indian-food-asian-cuisine_2829-6270.jpg?size=626&ext=jpg"},
                           {name: "Dal Makhni",
                            desc: "A creamy and flavorful lentil curry made with a combination of black lentils (urad dal) and kidney beans (rajma), simmered in a rich tomato-based gravy with aromatic spices. This comforting and wholesome dish is often enjoyed with rice or naan.",
                            price: "₹69",
                            imgURL: "https://img.freepik.com/premium-photo/indian-dhal-spicy-curry-bowl-spices-herbs-rustic-black-wooden-background_2829-4752.jpg?size=626&ext=jpg"}],
            breadBonaza: [{name: "Aloo Paratha",
                            desc: "Indulge in the warmth of a perfectly cooked paratha, crispy on the outside and generously stuffed with a spiced potato filling. As you tear into it, the savory aroma fills the air, and with each bite, the tender potatoes melt in your mouth, leaving you craving for more.",
                            price: "₹25",
                            imgURL: "https://static.toiimg.com/thumb/53109843.cms?imgsize=244340&width=800&height=800"},
                           {name: "Onion Kulcha",
                            desc: "Experience the delightful crunch as you bite into a golden-brown kulcha, revealing the tantalizing blend of onions and aromatic spices inside. The sweet-savory flavors dance on your taste buds, creating a symphony of tastes that perfectly complements your favorite curry.",
                            price: "₹19",
                            imgURL: "https://img.freepik.com/free-photo/delicious-assortment-traditional-roti_23-2149033985.jpg?size=626&ext=jpg"},
                           {name: "Masala Dosa",
                            desc: "Immerse yourself in the crispiness of a paper-thin dosa, folded over a delicious potato masala filling. With its golden, lacy edges and a delicate crunch, the dosa unveils a burst of flavors with every bite, taking you on a culinary journey to the flavors of South India.",
                            price: "₹69",
                            imgURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLHNEKsFkGWR1wowkM8m3pOq-AY6myPZc2jA&usqp=CAU"},
                           {name: "Puri",
                            desc: "Give in to the temptation of these golden orbs of delight, deep-fried to perfection. As you break into a hot and puffed puri, the irresistible aroma wafts through the air, leading you to a heavenly experience of dipping it into aromatic curries and relishing the crispiness as it melts in your mouth.",
                            price: "₹9",
                            imgURL: "https://img.freepik.com/premium-photo/puri-bhaji-indian-semi-dry-potato-spicy-recipe-also-known-as-batata-aloo-ki-sabji-served-with-fried-poori-selective-focus_466689-12820.jpg?size=626&ext=jpg"},
                           {name: "Roti",
                            desc: "Savor the simplicity of a warm, freshly made roti, with its softness and slight charred spots imparting a delightful texture. With its wholesome goodness, each tear of the soft bread is a comforting reminder of home-cooked meals and the joy of relishing it with your favorite curry.",
                            price: "₹7",
                            imgURL: "https://img.freepik.com/free-photo/homemade-wheat-tortillas-pita-bread-tortilla-pita-with-ingredients-cooking-white-table-top-view_127032-2505.jpg?size=626&ext=jpg"}],
            snackAttack: [{name: "Pakoras",
                            desc: "Deep-fried fritters made from a batter of gram flour and a variety of vegetables such as onions, spinach, or potatoes. With their crispy exterior and soft, flavorful interior, pakoras are a delightful snack option, especially when paired with tangy chutneys.",
                            price: "₹24",
                            imgURL: "https://pipingpotcurry.com/wp-content/uploads/2022/10/Air-fryer-onion-pakora-Piping-Pot-Curry-1.jpg"},
                           {name: "Bhel Puri",
                            desc: "A medley of puffed rice, sev (crunchy chickpea noodles), onions, tomatoes, chutneys, and a burst of tangy and spicy flavors. This iconic street snack offers a riot of textures and tastes, creating a harmonious blend of sweet, sour, and savory elements that will leave your taste buds dancing.",
                            price: "₹19",
                            imgURL: "https://upload.wikimedia.org/wikipedia/commons/2/20/Indian_cuisine-Chaat-Bhelpuri-03.jpg"},
                           {name: "Aloo Tikki",
                            desc: "Crispy potato patties, golden on the outside and soft on the inside, seasoned with spices and served with tangy tamarind chutney and refreshing mint chutney. These irresistible tikkis are a perfect snack to satisfy your cravings with their delightful combination of flavors and textures.",
                            price: "₹34",
                            imgURL: "https://img.freepik.com/free-photo/chicken-skewers-with-slices-apples-chili_2829-19997.jpg?size=626&ext=jpg"},
                           {name: "Samosas",
                            desc: "Crispy and golden pastry pockets filled with a savory mixture of spiced potatoes, peas, and aromatic spices. These triangular delights are a popular Indian street food, perfect for satisfying your snack cravings with their irresistible crunch and flavorful filling.",
                            price: "₹9",
                            imgURL: "https://img.freepik.com/free-photo/delicious-pakistani-food-with-tomato-sauce_23-2148825164.jpg?size=626&ext=jpg"}],
            refreshingBeverages:[{name: "Aam Panna",
                            desc: "A refreshing drink made from raw mango pulp, infused with spices like cumin, black salt, and mint leaves. Aam Panna is known for its sweet and tangy taste and is a popular summer cooler, helping to beat the heat and rejuvenate the body.",
                            price: "₹14",
                            imgURL: "https://img.freepik.com/free-photo/two-glasses-melon-juice-put-wooden-floor_1150-28039.jpg?size=626&ext=jpg"},
                           {name: "Thandai",
                            desc: "A traditional Indian drink made with a blend of soaked and ground almonds, cashews, melon seeds, and a mix of aromatic spices like cardamom, fennel, and saffron. Thandai is often served during festivals like Holi and provides a cooling and flavorful experience.",
                            price: "₹29",
                            imgURL: "https://img.freepik.com/free-photo/almond-milk-with-almond-marble-background_1150-45110.jpg?size=626&ext=jpg"},
                           {name: "Coconut Water",
                            desc: "The natural electrolyte-rich water found inside young coconuts is a popular and refreshing beverage in India. It is not only delicious but also hydrating, making it an excellent choice to quench your thirst and replenish essential minerals.",
                            price: "₹24",
                            imgURL: "https://img.freepik.com/free-photo/fresh-coconut-hand-with-plumeria-decorated-beach-with-sea-wave-tourist-with-fresh-fruit-sea-sand-sun-vacation-concept_1150-13508.jpg?size=626&ext=jpg"},
                           {name: "Lassi",
                            desc: "A popular yogurt-based drink available in sweet or savory variations. Sweet lassi is made with yogurt, sugar, and flavors like rose or mango, while savory lassi includes ingredients like salt, cumin, and mint. Lassi is creamy, refreshing, and a perfect accompaniment to spicy meals.",
                            price: "₹49",
                            imgURL: "https://img.freepik.com/free-photo/ayran-drink-with-mint-cucumber-glass-wooden-table_123827-21428.jpg?size=626&ext=jpg"},
                           {name: "Jaljeera",
                            desc: "A tangy and savory drink made with a blend of roasted cumin seeds, black salt, mint leaves, and tamarind pulp. Jaljeera is known for its cooling properties and is often enjoyed as a digestive drink, providing a burst of flavors that awaken the taste buds.",
                            price: "₹12",
                            imgURL: "https://img.freepik.com/free-photo/glasses-with-lemonade-table_23-2148482456.jpg?size=626&ext=jpg"}]},
  },
  {
    name: "Anjali Sharma",
    imgURL: "https://drive.google.com/uc?id=19s3ZXsi3wNAdkPKBbf-s-J7OVM_m6pzB",
    foodType: "south indian, punjabi",
    quote: "Homemade goodness that satisfies your cravings",
    rating: "4.2",
    noOfOrders: "122",
    minPrice: "79",
    dateOfJoining: "2023-10-2"
  },
  {
  name: "Divya Banerjee",
  imgURL: "https://drive.google.com/uc?id=1C7wtWLPKCSjedIXM2FHHDOvAdnwWxh3a",
  foodType: "north indian",
  quote: "Crafting flavors with love and passion",
  rating: "4.5",
  noOfOrders: "68",
  minPrice: "65",
  dateOfJoining: "2022-08-25"
  },
  {
  name: "Uma Sinha",
  imgURL: "https://drive.google.com/uc?id=1FcTB06vDEP0wdBwTR3s-PEXBYyJlb4Vq",
  foodType: "north indian, snacks",
  quote: "Indulge in the essence of homemade delicacies",
  rating: "4.2",
  noOfOrders: "45",
  minPrice: "99",
  dateOfJoining: "2022-12-12"
  },
  {
  name: "Suhani Suman",
  imgURL: "https://drive.google.com/uc?id=1QA_gDVsVsQKKpoBx-61nPRfnoDtgLPAH",
  foodType: "Indian snacks, Italian",
  quote: "Unleashing flavors that ignite your taste buds",
  rating: "4.2",
  noOfOrders: "48",
  minPrice: "75",
  dateOfJoining: "2022-07-15"
  },
  {
  name: "Mahima Banerjee",
  imgURL: "https://drive.google.com/uc?id=12lSdjVL2rPgeWb6zxqM_AuNwR3OTp6Qv",
  foodType: "Bengali Thali",
  quote: "A delightful journey through the taste of Bengal",
  rating: "3.8",
  noOfOrders: "56",
  minPrice: "55",
  dateOfJoining: "2023-09-22"
  },
  {
  name: "Priya mahajan",
  imgURL: "https://drive.google.com/uc?id=1vXzkhuZ-KjYKn2VV2_oZtbFY-M3TK_0A",
  foodType: "North Indian, snacks",
  quote: "Savor the essence of authentic homemade delicacies",
  rating: "3.7",
  noOfOrders: "64",
  minPrice: "89",
  dateOfJoining: "2023-09-13"
  },
  {
  name: "Anamika Singh",
  imgURL: "https://drive.google.com/uc?id=1aMY8cYpEZBSdtAB-Fwwqt7k0GxwZdCIQ",
  foodType: "north indian",
  quote: "Exploring the rich heritage of homemade flavors",
  rating: "4.4",
  noOfOrders: "92",
  minPrice: "75",
  dateOfJoining: "2023-05-23"
  },
  {
    name: "Astha Sharma",
    imgURL: "https://drive.google.com/uc?id=11SGHr8IKWTOuT4ka5bwO8oy8x1fQxJaM",
    foodType: "north indian, rajasthani",
    quote: "Indulge in the authentic taste of Marwari cuisine",
    rating: "4.2",
    noOfOrders: "76",
    minPrice: "90",
    dateOfJoining: "2023-09-18"
  },
  {
    name: "Daya Ben",
    imgURL: "https://drive.google.com/uc?id=18Kt-sE2qfMXlwEWXT-skSGlSQ1mrmZk8",
    foodType: "Gujrati Thali, snacks",
    quote: "Delight in the flavors of Gujarat with a variety of snacks",
    rating: "3.8",
    noOfOrders: "322",
    minPrice: "74",
    dateOfJoining: "2023-10-1"
  },
  {
    name: "Bhagyashree",
    imgURL: "https://drive.google.com/uc?id=1seS4n0j8bAMlNQHWs973QsY6IE-d4BQI",
    foodType: "Idli, Dosa, Upma, Vada",
    quote: "Experience a fusion of traditional Indian flavors with a modern twist",
    rating: "4.5",
    noOfOrders: "102",
    minPrice: "87",
    dateOfJoining: "2022-11-16"
  },
  {
    name: "Amrita Singh",
    imgURL: "https://drive.google.com/uc?id=1R7FJZBkK0JbIjhD3GYj4kjcnCSMYLWE3",
    foodType: "Rajasthani Thali",
    quote: "Savor the rich and aromatic flavors of North Indian and Mughlai cuisine",
    rating: "4.5",
    noOfOrders: "68",
    minPrice: "59",
    dateOfJoining: "2022-09-25"
  },
  {
    name: "Kiara sodi",
    imgURL: "https://drive.google.com/uc?id=16hn2BPGrkaWsnjcIzBlCTJB4Fav3OpPb",
    foodType: "Punjabi Thali",
    quote: "An amalgamation of South Indian and Indo-Chinese delicacies",
    rating: "4.2",
    noOfOrders: "72",
    minPrice: "84",
    dateOfJoining: "2023-09-18"
  },
  {
    name: "Bharti Verma",
    imgURL: "https://drive.google.com/uc?id=1ijWAHFjqBQoKIsQ09tYMZ9QYxnlHn_wl",
    foodType: "North Indian, Snacks",
    quote: "Savor the authentic taste of South India with our flavorful Kerala dishes",
    rating: "4.0",
    noOfOrders: "32",
    minPrice: "99",
    dateOfJoining: "2022-03-18"
  },
  {
    name: "Mithali",
    imgURL: "https://drive.google.com/uc?id=1OMfnlv6skATzzVRAIiAxLPXqwJ-XFpcD",
    foodType: "Punjabi Thali, snacks",
    quote: "Taste the authentic flavors of Bengal with our delectable fish curries and more",
    rating: "4.3",
    noOfOrders: "72",
    minPrice: "94",
    dateOfJoining: "2022-07-18"
  },
  {
    name: "Vedika Rama",
    imgURL: "https://drive.google.com/uc?id=1IwPDX1bThn_1HV9RpBposWlslBm4j5A9",
    foodType: "South Indian",
    quote: "Experience the opulence of Mughlai and Awadhi delicacies fit for the royals",
    rating: "4.4",
    noOfOrders: "54",
    minPrice: "64",
    dateOfJoining: "2022-03-25"
  },
  {
    name: "Raveena Tandon",
    imgURL: "https://drive.google.com/uc?id=1Hdy6eR8OZrSwU-ScobVzqRiPPycCI-MP",
    foodType: "North Indian",
    quote: "Indulge in the rich and aromatic flavors of Kashmir with our authentic Wazwan dishes",
    rating: "4.4",
    noOfOrders: "102",
    minPrice: "79",
    dateOfJoining: "2022-12-18"
  },
  {
    name: "Ishika Banerjee",
    imgURL: "https://drive.google.com/uc?id=1eswi42JsaoR3gJYQkrys0vnu8TM2lCzm",
    foodType: "Snacks, Bengali Sweets",
    quote: "Savor the traditional flavors of Gujarat and Rajasthan in every bite",
    rating: "4.6",
    noOfOrders: "132",
    minPrice: "69",
    dateOfJoining: "2023-01-25"
  },
  {
    name: "Tania Singh",
    imgURL: "https://drive.google.com/uc?id=1z9SSof0kld3NNEdhIyLpCguWDr8SV2bn",
    foodType: "Indian Snacks, Biryani",
    quote: "Experience the authentic flavors of Maharashtra and the coastal delights of Konkan",
    rating: "4.0",
    noOfOrders: "107",
    minPrice: "59",
    dateOfJoining: "2022-09-25"
  },
  {
    name: "Rashmika Dubey",
    imgURL: "https://drive.google.com/uc?id=1OFkUKqvOg4O5wHWwaPJgFg0jbwOCf60O",
    foodType: "Snacks, Momos",
    quote: "Tantalize your taste buds with the perfect blend of Indian and Chinese flavors",
    rating: "3.9",
    noOfOrders: "128",
    minPrice: "89",
    dateOfJoining: "2023-09-24"
  }
];

export default homecooks;
